- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0cda10cd2281e68bd  # replace with your SG ID
    zone_id: "Z086445618CDQ31LFJNM3" # replace with your ID
    domaim_name: "daws-86s.space"
    instances:
    - mongodb

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance.type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
       msg: "{{ ec2_output }}"
